massive update for libary :)
mhor-music/php-mp3info pull request #6
Opened 2017-12-11 09:22 UTC by ivoba

This lifts this library to work with newest dependecies.
I came across this library but it did not work with symfony4 components.

- >= PHP7.1
- >= symfony 3
- PSR-4
- removed uncessary docblocks where typehinting is sufficient
- adjusted usage of Process where ProcessBuilder was removed

2017-12-15 21:11 UTC, mhor requested changes
Wow thank you for your contributions.

2017-12-18 09:12 UTC, ivoba commented
@mhor requested changes are applied

2017-12-18 09:18 UTC, mhor approved these changes

2017-12-18 12:33 UTC, merged

2017-12-18 12:41 UTC, mhor commented
@ivoba merged and released as [1.0.0](https://github.com/mhor-music/php-mp3info/releases/tag/v1.0.0)